export const FETCH_QUIZZES_START = 'FETCH_QUIZZES_START';
export const FETCH_QUIZZES_FINISH = 'FETCH_QUIZZES_FINISH';
export const FETCH_QUIZZES_ERROR = 'FETCH_QUIZZES_ERROR';

export const FETCH_QUIZ_START = 'FETCH_QUIZ_START';
export const FETCH_QUIZ_FINISH = 'FETCH_QUIZ_FINISH';
export const FETCH_QUIZ_ERROR = 'FETCH_QUIZ_ERROR';

export const QUIZ_ANSWER_STATE = 'QUIZ_ANSWER_STATE';
export const QUIZ_ANSWER_NEXT = 'QUIZ_ANSWER_NEXT';
export const QUIZ_ANSWER_RESET = 'QUIZ_ANSWER_RESET';
